### ISSUE TITLE
Syntax highlighting (C++) not working

### ISSUE THREAD

**Issue by bilke** [panicinc/icarus#1]
Dear Panic team, thanks for this extension which is very useful for me, thanks a lot!

Unfortunately the syntax highlighting is not working at all for C++ files (e.g. `.h` and `.cpp` files). If I switch the language to `C` the highlighting works. Please note that previously I had [this C++ extension](https://github.com/tetraoxygen/Nova-CPP) installed which I have uninstalled now. I also tried to reinstall Icarus but it did not help. What else can I do?

**Comment by logancollins** [comment]
Thank you for the report! This looks to be due to a last-minute change I did not catch with integration of the C++ grammar. I have prepped v1.0.2 for release on the Nova Extension Library, which _should_ resolve this issue.

**Comment by bilke** [comment]
Awesome! Thanks for the quick fix!
