### ISSUE TITLE
Bug: LSP crashes when calling XCTAssertTrue before completion

### ISSUE THREAD

**Issue by alicerunsonfedora** [panicinc/icarus#17]
I noticed that, when writing unit tests using XCTest, the LSP will crash whenever I call `XCTAssertTrue` before I finish writing the condition:

```swift
final class MyTestCase: XCTestCase {
    func testExample() throws {
        XCTAssertTrue(|) // | is my cursor
    }
}
```

A workaround I've found was writing the condition first and wrapping it in parens, then add `XCTAssertTrue` before the wrapped expression.

**Comment by logancollins** [comment]
Unfortunately, a crash in SourceKit-LSP is outside of Icarus' domain. You may wish to file an issue [with the SourceKit-LSP project](https://github.com/apple/sourcekit-lsp).
