### ISSUE TITLE
Generated Source Code Not Recognized (Swift OpenAPI Generator )

### ISSUE THREAD

**Issue by ezfe** [panicinc/icarus#18]
I'm using the Swift OpenAPI generator and I've followed the basic tutorial they present (https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.1/tutorials/swift-openapi-generator) and it builds successfully, but in Nova it shows a bunch of errors - all claiming the auto-generated types don't exist.

Please advise

![Screenshot 2024-04-13 at 17 37 12@2x](https://github.com/panicinc/icarus/assets/1449259/058099dd-5354-4981-9974-4116448c00a9)

[SourceCode.zip](https://github.com/panicinc/icarus/files/14968714/SourceCode.zip)

edit: Note, the source code I attached is missing a dependency declaration (`.target(name: "ThemeParksSchema")`) however resolving this error does not resolve the reported problem.

**Comment by logancollins** [comment]
Unfortunately, this doesn't appear to be errors coming from Nova or Icarus themselves. It's coming from SourceKit-LSP (the language server which Icarus wraps, which is part of the Swift toolchain) and Swift Package Manager. If I open your example project, I see the same errors.
