### ISSUE TITLE
custom clangd configuration?

### ISSUE THREAD

**Issue by gknops** [panicinc/icarus#19]
I am using the plug-in for ESP-IDF development and for the most part it works well.

The only issue is that apparently the ESP-IDF toolchain uses some commands not known to clangd:
```
Unknown argument '-mlongcalls'; did you mean '-mlong-calls'?
Unknown argument: '-fno-shrink-wrap'
Unknown argument: '-fno-tree-switch-conversion'
Unknown argument: '-fstrict-volatile-bitfields'
```
And of course those show up for every source file.

So I wonder if I could add an ideally project-specific clangd configuration like so:

```
CompileFlags:
  Add: -Wno-unknown-warning-option 
  Remove: [-m*, -f*]
```

**Comment by gknops** [comment]
Turns out `.clangd` in any parent directory of the source file in question will work.

Sorry for the noise!

**Comment by gknops** [comment]
Thanks for this nice plugin!

**Comment by logancollins** [comment]
> Turns out `.clangd` in any parent directory of the source file in question will work.
> 
> Sorry for the noise!

No worries! I did not know this, that's good info, and glad you got it working.
