### ISSUE TITLE
Send stdin input to lldb debugger not responding

### ISSUE THREAD

**Issue by Goooyi** [panicinc/icarus#2]
I have a C code :
```C
printf("What's your First Name?");
in = fgets(you.first_name, MAX_DATA - 1,stdin);
```
When I launch the dubber, and hit this line, the bulit-in dubbger wait for me to give input (still not hitting break point yet, so the process is still running), as seen here:
![image](https://github.com/panicinc/icarus/assets/83227264/3f6305fe-7a4c-4ace-be3e-c75533d194e1)
But when I type something the built-in dubbger shell is not responding when I type in and thing and hit "Enter", 

Do I need to hit some shortcut or I' missing something?
Thanks

**Comment by logancollins** [comment]
Sorry for the delay in answering this.

This isn't supported by the Debug Adapter Protocol at the moment. Debugged executables cannot have their stdin rerouted in a way that the IDE can send data to it without being routed through, for example, a terminal.

We'll continue watching this to see if something is added, but for the moment this is sadly not possible.
