### ISSUE TITLE
Preview windows don't scale well 

### ISSUE THREAD

**Issue by parasaito** [panicinc/icarus#9]
The token preview on hover is a great feature, especially for looking up function prototypes. However some times it cannot autoscale appropriately. 

Consider these :

<img width="239" alt="Screenshot 2023-08-10 at 10 33 12 AM" src="https://github.com/panicinc/icarus/assets/97852663/b859a371-c7e0-49fe-ac91-7fe0f592aee1">

`const`, `char`, `restrict` all three on different lines. Also couldn't completely display restrict in arguments.

--- 
<img width="422" alt="Screenshot 2023-08-11 at 2 58 43 PM" src="https://github.com/panicinc/icarus/assets/97852663/9fa7c716-9c91-4b07-a02b-7aacb97eea4e">

This one is somewhat of extreme case due to parameter names, but displaying each parameter with it's (complete) type line-by-line would make it more readable.

---

These might look very minute details but it ultimately makes the code much less comprehensive.

REQUEST: Additionally, if possible, make the windows resizable using cursor, so worst case scenario users are able to read even if autoscaling fails.

**Comment by logancollins** [comment]
This is a known issue with Nova itself and we're tracking to hopefully have a fix in the future!
